export default () => ({
  // 首页部分
  loginType: '',
  currentMenu: '',
  token: '',
  // 管理部分
  editList: [],
  newTableList: [
    {
      id: 1,
      name: '浙江之声 1990-09-24',
      state: '节目',
      result: '',
      saveEdit: false,
      tableData: [
        { id: 1, date: "正题名", name: '杭州新闻 1991-05-12' },
        { id: 2, date: "首播日期", name: '1991-5-12' },
        { id: 3, date: "节目类型", name: '新闻' },
        { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
        { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
        { id: 6, date: "创建者名称", name: '杭州电视台' },
        { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
        { id: 8, date: "节目形态", name: '综合' },
        { id: 9, date: "栏目", name: '杭州新闻' },
        { id: 10, date: "色彩", name: '彩色' },
        { id: 11, date: "制式", name: 'PAL' },
        { id: 12, date: "声道格式", name: '单声道' },
        { id: 13, date: "画面宽高比", name: '4:3' },
        { id: 14, date: "入点", name: '00:00:00:19' },
        { id: 15, date: "时长", name: '00:11:10:12' },
        { id: 16, date: "资料获取方式", name: '自制' },
        { id: 17, date: "资料提供者", name: '杭州电视台' },
      ],
      imageData: [],
      children: [
        {
          id: 11,
          name: '杭州农药厂依靠科技进步',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '杭州农药厂依靠科技进步' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 12,
          name: '杭州市无偿献血活动日',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '杭州市无偿献血活动日' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 13,
          name: '本市医卫工作者开展“5.1”劳动节活动',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '本市医卫工作者开展“5.1”劳动节活动' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 14,
          name: '杭州户使学校培养合格护士',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '杭州户使学校培养合格护士' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 15,
          name: '我市举行小发明家成果发布会',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '我市举行小发明家成果发布会' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 16,
          name: '杭州西湖加斯总厂重视新发展',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '杭州西湖加斯总厂重视新发展' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 17,
          name: '斯迈尔到临安考察生态农业',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '斯迈尔到临安考察生态农业' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
        {
          id: 18,
          name: '龙翔桥农副产品时长抓好',
          state: '片段',
          result: '',
          saveEdit: false,
          tableData: [
            { id: 1, date: "正题名", name: '龙翔桥农副产品时长抓好' },
            { id: 2, date: "首播日期", name: '1991-5-12' },
            { id: 3, date: "节目类型", name: '新闻' },
            { id: 4, date: "内容描述", name: '1、向科技要效益————杭州农药厂依靠科技进步，提高经济效益 1、向科技要效益——杭州农药厂依靠科技进步，提高经济效益' },
            { id: 5, date: "字幕形式", name: '只有画面叠加字幕' },
            { id: 6, date: "创建者名称", name: '杭州电视台' },
            { id: 7, date: "其他责任者项", name: '编辑：赵良，行首电视台；编辑：孟丽，杭州电视台；播音：闫倩，杭州电视台' },
            { id: 8, date: "节目形态", name: '综合' },
            { id: 9, date: "栏目", name: '杭州新闻' },
            { id: 10, date: "色彩", name: '彩色' },
            { id: 11, date: "制式", name: 'PAL' },
            { id: 12, date: "声道格式", name: '单声道' },
            { id: 13, date: "画面宽高比", name: '4:3' },
            { id: 14, date: "入点", name: '00:00:00:19' },
            { id: 15, date: "时长", name: '00:11:10:12' },
            { id: 16, date: "资料获取方式", name: '自制' },
            { id: 17, date: "资料提供者", name: '杭州电视台' },
          ],
          imageData: [],
        },
      ]
    }
  ]
})